# Generated by Django 4.0.6 on 2022-08-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NottyApp', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
